sudo: required

language: generic

services:
 - docker

before_install:
 - echo "start"
 - docker build -t minju7346/react -f dockerfile.dev .

script:
 - docker system prune
 - y
 - docker run -e CI=true minju7346/react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  edge: true
  region: "ap-northeast-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-622813943817"
  bucker_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  